name: Deploy Python App

on:
  push:
    branches: [ main ]

jobs:
  docker_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/dll-app:latest

  deploy:
    needs: docker_deploy
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/dll-app:latest
            
            docker stop dll-app || true
            docker rm dll-app || true
            docker image prune -f

            docker run -d \
              --name dll-app \
              --restart always \
              -p 5000:5000 \
              ${{ secrets.DOCKERHUB_USERNAME }}/dll-app:latest
